### ISSUE TITLE
[AdKats] ERROR-7000: 

### ISSUE THREAD

**Issue by hemaniaco** [ColColonCleaner/AdKats_Engine#9]
After couple tries I think I followed every single step. I manage to add one Full Admin user, when i try to add more i get that:

[19:15:50 35] [AdKats] EXCEPTION-7000-D-BuildRoleSettings-AccessFetching27: [Error building role setting section.][System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.ThrowHelper.ThrowKeyNotFoundException()
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei PRoConEvents.AdKats.BuildRoleSettings(List`1 lstReturn)]

**Comment by ColColonCleaner** [comment]
Reboot your procon layer.
Start AdKats and wait for it to completely boot.
run /pupdate from the procon chat tab.
After the update is complete, reboot your procon layer again.
See if the error still exists.

**Comment by hemaniaco** [comment]
That was a very very quick response! Worked for me! Thank you very much!

**Comment by ColColonCleaner** [comment]
Glad it worked. Cheers.

In the future please use the actual AdKats repository instead of the engine. This engine is not released yet.

https://github.com/AdKats/AdKats/issues
